### ISSUE TITLE
Audio Triggers

### ISSUE THREAD

**Issue by KadeBehm** [AvolitesLtd/TitanManual#74]
**Link to the page in the manual:**
https://manual.avolites.com/docs/running-the-show/midi-dmx-or-audio-triggering/

**Old Text (if applicable):**
If the console does not have suitable hardware a warning message is displayed. Currently only the Quartz and Arena consoles have the audio hardware.

**New Text:**
If the console does not have suitable hardware a warning message is displayed. Currently only the T2, Quartz and Arena consoles have the audio hardware. The T2 can be used to add this feature to other consoles(except T1) 

**Why it should be changed:**
Because the original text is wrong. 

**Other Information:**
Any other information

**Comment by KadeBehm** [comment]
Actually I see this has been added , I was working out of the PDF . My mistake I'll check the section on-line before I submit in the future.

**Comment by KadeBehm** [comment]
Actually no it still says in the audio triggers section that only quartz and arena  as I pasted above .

**Comment by congoblue** [comment]
The quoted text is from the v12 manual - this has already been corrected in the later updates to the manual (v13 and v13+). The text now lists the consoles which do not have audio hardware as it is anticipated that all consoles will eventually have this hardware.

**Comment by Farrser** [comment]
It looks like the quoted text still exists here?

"If the console does not have suitable hardware a warning message is displayed. Currently only the Quartz and Arena consoles have the audio hardware."

As Kade says I think the T2 also does Audio

https://manual.avolites.com/docs/next/running-the-show/midi-dmx-or-audio-triggering/#audio-control-sound-to-light

**Comment by KadeBehm** [comment]
Hey Tim 

 Except the quoted text is from the v13 PDF and is also in the online manual 


See Screen shot. boxed in red. 



Kade Behm
(303)944-4504
clublights@mac.com

**Comment by congoblue** [comment]
Ah sorry I was looking at the start of the section where this text also existed. Will fix for next version.

**Comment by congoblue** [comment]
Fixed for next update (referred to list at top of section to avoid this getting missed again in the future).
